name: customer_pos_transform
version: '1.0'
config-version: 2

profile: default

models:
  customer_pos_transform:       # this should match your project name
    +schema: TRANSFORMED_POS    # force schema to always be this
    +materialized: table        # optional: make all models materialized as tables
